branch-defaults:
  default:
    environment: kean-env
environment-defaults:
  kean-env:
    branch: null
    repository: null
global:
  application_name: kean
  default_ec2_keyname: kean-keypair
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.4 running
    on 64bit Amazon Linux/2.4.0
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
